apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-multioption-cloud 
  janus-idp.io/tekton: test-multioption-cloud
  backstage.io/kubernetes-id: test-multioption-cloud
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-multioption-cloud
resources: 
- application-dev.yaml